<?php
/********************************************************************************
*  Copyright 2015 Conab - Companhia Nacional de Abastecimento                   *
*                                                                               *
*  Este arquivo é parte do Sistema SIAUDI.                                      *
*                                                                               *
*  SIAUDI  é um software livre; você pode redistribui-lo e/ou                   *
*  modificá-lo sob os termos da Licença Pública Geral GNU conforme              *
*  publicada pela Free Software Foundation; tanto a versão 2 da                 *
*  Licença, como (a seu critério) qualquer versão posterior.                    *
*                                                                               *
*  SIAUDI é distribuído na expectativa de que seja útil,                        *
*  porém, SEM NENHUMA GARANTIA; nem mesmo a garantia implícita                  *
*  de COMERCIABILIDADE OU ADEQUAÇÃO A UMA FINALIDADE ESPECÍFICA.                *
*  Consulte a Licença Pública Geral do GNU para mais detalhes em português:     *
*  http://creativecommons.org/licenses/GPL/2.0/legalcode.pt                     *
*                                                                               *
*  Você deve ter recebido uma cópia da Licença Pública Geral do GNU             *
*  junto com este programa; se não, escreva para a Free Software                *
*  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA    *
*                                                                               *
*  Sistema   : SIAUDI - Sistema de Auditoria Interna                            *
*  Data      : 05/2015                                                          *
*                                                                               *
********************************************************************************/
?>
<?php

/**
 * This is the model base class for the table "{{homens_hora_conf}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "HomensHoraConf".
 *
 * Columns in table "{{homens_hora_conf}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $valor_exercicio
 * @property string $descricao_act
 *
 */
abstract class BaseHomensHoraConf extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{homens_hora_conf}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Homens Hora Configuração|Homens Hora Configurações', $n);
	}

	public static function representingColumn() {
		return 'descricao_act';
	}

	public function rules() {
		return array(
			array('valor_exercicio, descricao_act', 'required'),
			array('valor_exercicio', 'numerical', 'integerOnly'=>true),
			array('descricao_act', 'length', 'max'=>1000),
			array('valor_exercicio, descricao_act', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'valor_exercicio' => Yii::t('app', 'Valor Exercicio'),
			'descricao_act' => Yii::t('app', 'Descricao Act'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('valor_exercicio', $this->valor_exercicio);
		$criteria->compare('descricao_act', $this->descricao_act, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}