<?php
/********************************************************************************
*  Copyright 2015 Conab - Companhia Nacional de Abastecimento                   *
*                                                                               *
*  Este arquivo é parte do Sistema SIAUDI.                                      *
*                                                                               *
*  SIAUDI  é um software livre; você pode redistribui-lo e/ou                   *
*  modificá-lo sob os termos da Licença Pública Geral GNU conforme              *
*  publicada pela Free Software Foundation; tanto a versão 2 da                 *
*  Licença, como (a seu critério) qualquer versão posterior.                    *
*                                                                               *
*  SIAUDI é distribuído na expectativa de que seja útil,                        *
*  porém, SEM NENHUMA GARANTIA; nem mesmo a garantia implícita                  *
*  de COMERCIABILIDADE OU ADEQUAÇÃO A UMA FINALIDADE ESPECÍFICA.                *
*  Consulte a Licença Pública Geral do GNU para mais detalhes em português:     *
*  http://creativecommons.org/licenses/GPL/2.0/legalcode.pt                     *
*                                                                               *
*  Você deve ter recebido uma cópia da Licença Pública Geral do GNU             *
*  junto com este programa; se não, escreva para a Free Software                *
*  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA    *
*                                                                               *
*  Sistema   : SIAUDI - Sistema de Auditoria Interna                            *
*  Data      : 05/2015                                                          *
*                                                                               *
********************************************************************************/
?>
<?php

/**
 * This is the model base class for the table "{{feriado}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Feriado".
 *
 * Columns in table "{{feriado}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $data_feriado
 * @property string $nome_feriado
 *
 */
abstract class BaseFeriado extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{feriado}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Feriado|Feriados', $n);
	}

	public static function representingColumn() {
		return 'nome_feriado';
	}

	public function rules() {
		return array(
			array('data_feriado, nome_feriado, repetir_todo_ano', 'required'),
			array('nome_feriado', 'length', 'max'=>60),
			array('data_feriado, nome_feriado', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'data_feriado' => Yii::t('app', 'Data'),
			'nome_feriado' => Yii::t('app', 'Descrição'),
			'repetir_todo_ano' => Yii::t('app', 'Repetir todo ano'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('data_feriado', $this->data_feriado, true);
                if ($this->nome_feriado){
                        $criteria->condition="nome_feriado ilike :input";
                        $criteria->params=array(":input"=>"%".$this->nome_feriado."%");
                }

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}