<?php
/********************************************************************************
*  Copyright 2015 Conab - Companhia Nacional de Abastecimento                   *
*                                                                               *
*  Este arquivo é parte do Sistema SIAUDI.                                      *
*                                                                               *
*  SIAUDI  é um software livre; você pode redistribui-lo e/ou                   *
*  modificá-lo sob os termos da Licença Pública Geral GNU conforme              *
*  publicada pela Free Software Foundation; tanto a versão 2 da                 *
*  Licença, como (a seu critério) qualquer versão posterior.                    *
*                                                                               *
*  SIAUDI é distribuído na expectativa de que seja útil,                        *
*  porém, SEM NENHUMA GARANTIA; nem mesmo a garantia implícita                  *
*  de COMERCIABILIDADE OU ADEQUAÇÃO A UMA FINALIDADE ESPECÍFICA.                *
*  Consulte a Licença Pública Geral do GNU para mais detalhes em português:     *
*  http://creativecommons.org/licenses/GPL/2.0/legalcode.pt                     *
*                                                                               *
*  Você deve ter recebido uma cópia da Licença Pública Geral do GNU             *
*  junto com este programa; se não, escreva para a Free Software                *
*  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA    *
*                                                                               *
*  Sistema   : SIAUDI - Sistema de Auditoria Interna                            *
*  Data      : 05/2015                                                          *
*                                                                               *
********************************************************************************/
?>
<?php

/**
 * This is the model base class for the table "vw_sureg".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Sureg".
 *
 * Columns in table "vw_sureg" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $nome
 * @property string $sigla
 * @property string $uf_fk
 * @property string $subordinante_fk
 *
 */
abstract class BaseVwUnidadeAdministrativa extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'vw_unidade_administrativa';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Unidade Administrativa (Lotação)|Unidades Administrativas (Lotações)', $n);
	}

	public static function representingColumn() {
		return 'nome';
	}

	public function rules() {
		return array(
			array('id, subordinante_fk, sigla', 'safe'),
			array('id, subordinante_fk', 'numerical', 'integerOnly'=>true),
			array('id, nome, sigla, uf_fk, subordinante_fk', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'nome' => Yii::t('app', 'Nome'),
			'sigla' => Yii::t('app', 'Sigla'),
			'uf_fk' => Yii::t('app', 'Uf Fk'),
			'subordinante_fk' => Yii::t('app', 'Subordinante Fk'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;
		$criteria->compare('id', $this->id, true);
		$criteria->compare('nome', $this->nome, true);
		$criteria->compare('sigla', $this->sigla, true);
		$criteria->compare('uf_fk', $this->uf_fk, true);
		$criteria->compare('subordinante_fk', $this->subordinante_fk, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}