<?php
/********************************************************************************
*  Copyright 2015 Conab - Companhia Nacional de Abastecimento                   *
*                                                                               *
*  Este arquivo é parte do Sistema SIAUDI.                                      *
*                                                                               *
*  SIAUDI  é um software livre; você pode redistribui-lo e/ou                   *
*  modificá-lo sob os termos da Licença Pública Geral GNU conforme              *
*  publicada pela Free Software Foundation; tanto a versão 2 da                 *
*  Licença, como (a seu critério) qualquer versão posterior.                    *
*                                                                               *
*  SIAUDI é distribuído na expectativa de que seja útil,                        *
*  porém, SEM NENHUMA GARANTIA; nem mesmo a garantia implícita                  *
*  de COMERCIABILIDADE OU ADEQUAÇÃO A UMA FINALIDADE ESPECÍFICA.                *
*  Consulte a Licença Pública Geral do GNU para mais detalhes em português:     *
*  http://creativecommons.org/licenses/GPL/2.0/legalcode.pt                     *
*                                                                               *
*  Você deve ter recebido uma cópia da Licença Pública Geral do GNU             *
*  junto com este programa; se não, escreva para a Free Software                *
*  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA    *
*                                                                               *
*  Sistema   : SIAUDI - Sistema de Auditoria Interna                            *
*  Data      : 05/2015                                                          *
*                                                                               *
********************************************************************************/
?>
<?php

/**
 * This is the model base class for the table "{{log_entrada}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "LogEntrada".
 *
 * Columns in table "{{log_entrada}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $nome_login
 * @property string $data_entrada
 * @property string $valor_ip
 * @property string $id
 *
 */
abstract class BaseLogEntrada extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{log_entrada}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'LogEntrada|LogEntradas', $n);
	}

	public static function representingColumn() {
		return 'nome_login';
	}

	public function rules() {
		return array(
			array('nome_login, data_entrada', 'required'),
			array('nome_login', 'length', 'max'=>100),
			array('valor_ip', 'length', 'max'=>23),
			array('nome_login, data_entrada, valor_ip, id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'nome_login' => Yii::t('app', 'Nome Login'),
			'data_entrada' => Yii::t('app', 'Data Entrada'),
			'valor_ip' => Yii::t('app', 'Valor Ip'),
			'id' => Yii::t('app', 'ID'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('nome_login', $this->nome_login, true);
		$criteria->compare('data_entrada', $this->data_entrada, true);
		$criteria->compare('valor_ip', $this->valor_ip, true);
		$criteria->compare('id', $this->id, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}