<?php
/********************************************************************************
*  Copyright 2015 Conab - Companhia Nacional de Abastecimento                   *
*                                                                               *
*  Este arquivo é parte do Sistema SIAUDI.                                      *
*                                                                               *
*  SIAUDI  é um software livre; você pode redistribui-lo e/ou                   *
*  modificá-lo sob os termos da Licença Pública Geral GNU conforme              *
*  publicada pela Free Software Foundation; tanto a versão 2 da                 *
*  Licença, como (a seu critério) qualquer versão posterior.                    *
*                                                                               *
*  SIAUDI é distribuído na expectativa de que seja útil,                        *
*  porém, SEM NENHUMA GARANTIA; nem mesmo a garantia implícita                  *
*  de COMERCIABILIDADE OU ADEQUAÇÃO A UMA FINALIDADE ESPECÍFICA.                *
*  Consulte a Licença Pública Geral do GNU para mais detalhes em português:     *
*  http://creativecommons.org/licenses/GPL/2.0/legalcode.pt                     *
*                                                                               *
*  Você deve ter recebido uma cópia da Licença Pública Geral do GNU             *
*  junto com este programa; se não, escreva para a Free Software                *
*  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA    *
*                                                                               *
*  Sistema   : SIAUDI - Sistema de Auditoria Interna                            *
*  Data      : 05/2015                                                          *
*                                                                               *
********************************************************************************/
?>
<?php

/**
 * This is the model base class for the table "{{recomendacao_categoria}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "RecomendacaoCategoria".
 *
 * Columns in table "{{recomendacao_categoria}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $nome_categoria
 *
 */
abstract class BaseRecomendacaoCategoria extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{recomendacao_categoria}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Categoria da Recomendação|Categorias da Recomendação', $n);
	}

	public static function representingColumn() {
		return 'nome_categoria';
	}

	public function rules() {
		return array(
			array('nome_categoria', 'required'),
			array('nome_categoria', 'length', 'max'=>200),
			array('id, nome_categoria', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'nome_categoria' => Yii::t('app', 'Nome Categoria'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
                if ($this->nome_categoria){
                        $criteria->condition="nome_categoria ilike :input";
                        $criteria->params=array(":input"=>"%".$this->nome_categoria."%");
                }                    
		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}