<?php
/********************************************************************************
*  Copyright 2015 Conab - Companhia Nacional de Abastecimento                   *
*                                                                               *
*  Este arquivo é parte do Sistema SIAUDI.                                      *
*                                                                               *
*  SIAUDI  é um software livre; você pode redistribui-lo e/ou                   *
*  modificá-lo sob os termos da Licença Pública Geral GNU conforme              *
*  publicada pela Free Software Foundation; tanto a versão 2 da                 *
*  Licença, como (a seu critério) qualquer versão posterior.                    *
*                                                                               *
*  SIAUDI é distribuído na expectativa de que seja útil,                        *
*  porém, SEM NENHUMA GARANTIA; nem mesmo a garantia implícita                  *
*  de COMERCIABILIDADE OU ADEQUAÇÃO A UMA FINALIDADE ESPECÍFICA.                *
*  Consulte a Licença Pública Geral do GNU para mais detalhes em português:     *
*  http://creativecommons.org/licenses/GPL/2.0/legalcode.pt                     *
*                                                                               *
*  Você deve ter recebido uma cópia da Licença Pública Geral do GNU             *
*  junto com este programa; se não, escreva para a Free Software                *
*  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA    *
*                                                                               *
*  Sistema   : SIAUDI - Sistema de Auditoria Interna                            *
*  Data      : 05/2015                                                          *
*                                                                               *
********************************************************************************/
?>
<?php

/**
 * This is the model base class for the table "{{plan_especifico_auditor}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PlanEspecificoAuditor".
 *
 * Columns in table "{{plan_especifico_auditor}}" available as properties of the model,
 * followed by relations of table "{{plan_especifico_auditor}}" available as properties of the model.
 *
 * @property string $plan_especifico_fk
 * @property string $auditor_fk
 *
 * @property mixed $planEspecificoFk
 */
abstract class BasePlanEspecificoAuditor extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{plan_especifico_auditor}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Planejamento Específico Auditor|Planejamento Específico Auditores', $n);
	}

	public static function representingColumn() {
		return 'plan_especifico_fk';
	}

	public function rules() {
		return array(
			array('plan_especifico_fk, usuario_fk, plan_auditor', 'required'),
			array('plan_especifico_fk, usuario_fk', 'numerical', 'integerOnly'=>true),
			array('plan_especifico_fk, usuario_fk', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'planEspecificoFk' => array(self::BELONGS_TO, 'PlanEspecifico', 'plan_especifico_fk'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'plan_especifico_fk' => null,
			'usuario_fk' => Yii::t('app', 'Auditor Fk'),
			'planEspecificoFk' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('plan_especifico_fk', $this->plan_especifico_fk);
		$criteria->compare('usuario_fk', $this->usuario_fk, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}