<?php
/********************************************************************************
*  Copyright 2015 Conab - Companhia Nacional de Abastecimento                   *
*                                                                               *
*  Este arquivo é parte do Sistema SIAUDI.                                      *
*                                                                               *
*  SIAUDI  é um software livre; você pode redistribui-lo e/ou                   *
*  modificá-lo sob os termos da Licença Pública Geral GNU conforme              *
*  publicada pela Free Software Foundation; tanto a versão 2 da                 *
*  Licença, como (a seu critério) qualquer versão posterior.                    *
*                                                                               *
*  SIAUDI é distribuído na expectativa de que seja útil,                        *
*  porém, SEM NENHUMA GARANTIA; nem mesmo a garantia implícita                  *
*  de COMERCIABILIDADE OU ADEQUAÇÃO A UMA FINALIDADE ESPECÍFICA.                *
*  Consulte a Licença Pública Geral do GNU para mais detalhes em português:     *
*  http://creativecommons.org/licenses/GPL/2.0/legalcode.pt                     *
*                                                                               *
*  Você deve ter recebido uma cópia da Licença Pública Geral do GNU             *
*  junto com este programa; se não, escreva para a Free Software                *
*  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA    *
*                                                                               *
*  Sistema   : SIAUDI - Sistema de Auditoria Interna                            *
*  Data      : 05/2015                                                          *
*                                                                               *
********************************************************************************/
?>
<?php

/**
 * This is the model base class for the table "{{processo_especie_auditoria}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ProcessoEspecieAuditoria".
 *
 * Columns in table "{{processo_especie_auditoria}}" available as properties of the model,
 * followed by relations of table "{{processo_especie_auditoria}}" available as properties of the model.
 *
 * @property integer $processo_fk
 * @property integer $especie_auditoria_fk
 *
 * @property mixed $processoFk
 * @property mixed $especieAuditoriaFk
 */
abstract class BaseProcessoEspecieAuditoria extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{processo_especie_auditoria}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ProcessoEspecieAuditoria|ProcessoEspecieAuditorias', $n);
	}

	public static function representingColumn() {
		return 'processo_fk';
	}

	public function rules() {
		return array(
			array('processo_fk, especie_auditoria_fk', 'required'),
			array('processo_fk, especie_auditoria_fk', 'numerical', 'integerOnly'=>true),
			array('processo_fk, especie_auditoria_fk', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'processoFk' => array(self::BELONGS_TO, 'processo', 'processo_fk'),
			'especieAuditoriaFk' => array(self::BELONGS_TO, 'EspecieAuditoria', 'especie_auditoria_fk'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'processo_fk' => null,
			'especie_auditoria_fk' => null,
			'processoFk' => null,
			'especieAuditoriaFk' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('processo_fk', $this->processo_fk);
		$criteria->compare('especie_auditoria_fk', $this->especie_auditoria_fk);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}