<?php
/********************************************************************************
*  Copyright 2015 Conab - Companhia Nacional de Abastecimento                   *
*                                                                               *
*  Este arquivo é parte do Sistema SIAUDI.                                      *
*                                                                               *
*  SIAUDI  é um software livre; você pode redistribui-lo e/ou                   *
*  modificá-lo sob os termos da Licença Pública Geral GNU conforme              *
*  publicada pela Free Software Foundation; tanto a versão 2 da                 *
*  Licença, como (a seu critério) qualquer versão posterior.                    *
*                                                                               *
*  SIAUDI é distribuído na expectativa de que seja útil,                        *
*  porém, SEM NENHUMA GARANTIA; nem mesmo a garantia implícita                  *
*  de COMERCIABILIDADE OU ADEQUAÇÃO A UMA FINALIDADE ESPECÍFICA.                *
*  Consulte a Licença Pública Geral do GNU para mais detalhes em português:     *
*  http://creativecommons.org/licenses/GPL/2.0/legalcode.pt                     *
*                                                                               *
*  Você deve ter recebido uma cópia da Licença Pública Geral do GNU             *
*  junto com este programa; se não, escreva para a Free Software                *
*  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA    *
*                                                                               *
*  Sistema   : SIAUDI - Sistema de Auditoria Interna                            *
*  Data      : 05/2015                                                          *
*                                                                               *
********************************************************************************/
?>
<?php

/**
 * This is the model base class for the table "{{recomendacao_subcategoria}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "RecomendacaoSubcategoria".
 *
 * Columns in table "{{recomendacao_subcategoria}}" available as properties of the model,
 * followed by relations of table "{{recomendacao_subcategoria}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $recomendacao_categoria_fk
 * @property string $nome_subcategoria
 *
 * @property mixed $recomendacaoCategoriaFk
 */
abstract class BaseRecomendacaoSubcategoria extends GxActiveRecord {

	public static function model($className = __CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{recomendacao_subcategoria}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Subcategoria da Recomendação|Subcategorias da Recomendação', $n);
	}

	public static function representingColumn() {
		return 'nome_subcategoria';
	}

	public function rules() {
		return array(
		array('recomendacao_categoria_fk, nome_subcategoria', 'required'),
		array('recomendacao_categoria_fk', 'numerical', 'integerOnly' => true),
		array('nome_subcategoria', 'length', 'max' => 200),
		array('id, recomendacao_categoria_fk, nome_subcategoria', 'safe', 'on' => 'search'),
		);
	}

	public function relations() {
		return array(
            'recomendacaoCategoriaFk' => array(self::BELONGS_TO, 'RecomendacaoCategoria', 'recomendacao_categoria_fk'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
            'id' => Yii::t('app', 'ID'),
            'recomendacao_categoria_fk' => null,
            'nome_subcategoria' => Yii::t('app', 'Nome Subcategoria'),
            'recomendacaoCategoriaFk' => null,
		);
	}

    public function search() {
        $schema = Yii::app()->params['schema'];        
        $criteria = new CDbCriteria;
        
        $criteria->alias = "t";
        $criteria->compare('id', $this->id);
        $criteria->compare('recomendacao_categoria_fk', $this->recomendacao_categoria_fk);
        $criteria->compare('nome_subcategoria', $this->nome_subcategoria, true);
        
        $criteria->join = "LEFT JOIN {$schema}.tb_recomendacao_categoria categoria ON t.recomendacao_categoria_fk=categoria.id";
        $criteria->order='categoria.nome_categoria, t.nome_subcategoria';


		return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
		));
	}

}