<?php
/********************************************************************************
*  Copyright 2015 Conab - Companhia Nacional de Abastecimento                   *
*                                                                               *
*  Este arquivo é parte do Sistema SIAUDI.                                      *
*                                                                               *
*  SIAUDI  é um software livre; você pode redistribui-lo e/ou                   *
*  modificá-lo sob os termos da Licença Pública Geral GNU conforme              *
*  publicada pela Free Software Foundation; tanto a versão 2 da                 *
*  Licença, como (a seu critério) qualquer versão posterior.                    *
*                                                                               *
*  SIAUDI é distribuído na expectativa de que seja útil,                        *
*  porém, SEM NENHUMA GARANTIA; nem mesmo a garantia implícita                  *
*  de COMERCIABILIDADE OU ADEQUAÇÃO A UMA FINALIDADE ESPECÍFICA.                *
*  Consulte a Licença Pública Geral do GNU para mais detalhes em português:     *
*  http://creativecommons.org/licenses/GPL/2.0/legalcode.pt                     *
*                                                                               *
*  Você deve ter recebido uma cópia da Licença Pública Geral do GNU             *
*  junto com este programa; se não, escreva para a Free Software                *
*  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA    *
*                                                                               *
*  Sistema   : SIAUDI - Sistema de Auditoria Interna                            *
*  Data      : 05/2015                                                          *
*                                                                               *
********************************************************************************/
?>
<?php

/**
 * This is the model base class for the table "{{acao_mes}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AcaoMes".
 *
 * Columns in table "{{acao_mes}}" available as properties of the model,
 * followed by relations of table "{{acao_mes}}" available as properties of the model.
 *
 * @property string $acao_fk
 * @property integer $numero_mes
 *
 * @property mixed $acaoFk
 */
abstract class BaseAcaoMes extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{acao_mes}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Mês da Ação |Meses da Ação', $n);
	}

	public static function representingColumn() {
		return 'acao_fk';
	}

	public function rules() {
		return array(
			array('acao_fk, numero_mes', 'required'),
			array('numero_mes', 'numerical', 'integerOnly'=>true),
			array('acao_fk, numero_mes', 'numerical', 'integerOnly'=>true),
			array('acao_fk, numero_mes', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'acaoFk' => array(self::BELONGS_TO, 'acao', 'acao_fk'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'acao_fk' => null,
			'numero_mes' => Yii::t('app', 'Numero Mes'),
			'acaoFk' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('acao_fk', $this->acao_fk);
		$criteria->compare('numero_mes', $this->numero_mes);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}