<?php
/********************************************************************************
*  Copyright 2015 Conab - Companhia Nacional de Abastecimento                   *
*                                                                               *
*  Este arquivo é parte do Sistema SIAUDI.                                      *
*                                                                               *
*  SIAUDI  é um software livre; você pode redistribui-lo e/ou                   *
*  modificá-lo sob os termos da Licença Pública Geral GNU conforme              *
*  publicada pela Free Software Foundation; tanto a versão 2 da                 *
*  Licença, como (a seu critério) qualquer versão posterior.                    *
*                                                                               *
*  SIAUDI é distribuído na expectativa de que seja útil,                        *
*  porém, SEM NENHUMA GARANTIA; nem mesmo a garantia implícita                  *
*  de COMERCIABILIDADE OU ADEQUAÇÃO A UMA FINALIDADE ESPECÍFICA.                *
*  Consulte a Licença Pública Geral do GNU para mais detalhes em português:     *
*  http://creativecommons.org/licenses/GPL/2.0/legalcode.pt                     *
*                                                                               *
*  Você deve ter recebido uma cópia da Licença Pública Geral do GNU             *
*  junto com este programa; se não, escreva para a Free Software                *
*  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA    *
*                                                                               *
*  Sistema   : SIAUDI - Sistema de Auditoria Interna                            *
*  Data      : 05/2015                                                          *
*                                                                               *
********************************************************************************/
?>
<?php

/**
 * This is the model base class for the table "{{processo}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Processo".
 *
 * Columns in table "{{processo}}" available as properties of the model,
 * followed by relations of table "{{processo}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $nome_processo
 * @property integer $tipo_processo_fk
 * @property integer $valor_exercicio
 *
 * @property mixed $tipoProcessoFk
 */
abstract class BaseProcesso extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{processo}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Processo|Processos', $n);
	}

	public static function representingColumn() {
		return 'nome_processo';
	}

	public function rules() {
		return array(
			array('valor_exercicio, nome_processo, tipo_processo_fk, repetir_todo_ano', 'required'),
			array('id, tipo_processo_fk, valor_exercicio', 'numerical', 'integerOnly'=>true),
			array('nome_processo', 'length', 'max'=>200),
			array('id, nome_processo, tipo_processo_fk, valor_exercicio', 'safe', 'on'=>'search'),
		);
	}
        

	public function relations() {
		return array(
			'tipoProcessoFk' => array(self::BELONGS_TO, 'TipoProcesso', 'tipo_processo_fk'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'nome_processo' => Yii::t('app', 'Nome Processo'),
			'tipo_processo_fk' => null,
			'valor_exercicio' => Yii::t('app', 'Valor Exercicio'),
			'tipoProcessoFk' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
                if ($this->nome_processo){
                        $criteria->condition="nome_processo ilike :input";
                        $criteria->params=array(":input"=>"%".$this->nome_processo."%");
                }                
		$criteria->compare('tipo_processo_fk', $this->tipo_processo_fk);
		$criteria->compare('valor_exercicio', $this->valor_exercicio);
                $criteria->order = 'valor_exercicio, nome_processo';
		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}