<?php
/********************************************************************************
*  Copyright 2015 Conab - Companhia Nacional de Abastecimento                   *
*                                                                               *
*  Este arquivo é parte do Sistema SIAUDI.                                      *
*                                                                               *
*  SIAUDI  é um software livre; você pode redistribui-lo e/ou                   *
*  modificá-lo sob os termos da Licença Pública Geral GNU conforme              *
*  publicada pela Free Software Foundation; tanto a versão 2 da                 *
*  Licença, como (a seu critério) qualquer versão posterior.                    *
*                                                                               *
*  SIAUDI é distribuído na expectativa de que seja útil,                        *
*  porém, SEM NENHUMA GARANTIA; nem mesmo a garantia implícita                  *
*  de COMERCIABILIDADE OU ADEQUAÇÃO A UMA FINALIDADE ESPECÍFICA.                *
*  Consulte a Licença Pública Geral do GNU para mais detalhes em português:     *
*  http://creativecommons.org/licenses/GPL/2.0/legalcode.pt                     *
*                                                                               *
*  Você deve ter recebido uma cópia da Licença Pública Geral do GNU             *
*  junto com este programa; se não, escreva para a Free Software                *
*  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA    *
*                                                                               *
*  Sistema   : SIAUDI - Sistema de Auditoria Interna                            *
*  Data      : 05/2015                                                          *
*                                                                               *
********************************************************************************/
?>
<?php

/**
 * This is the model base class for the table "{{subrisco}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Subrisco".
 *
 * Columns in table "{{subrisco}}" available as properties of the model,
 * followed by relations of table "{{subrisco}}" available as properties of the model.
 *
 * @property string $id
 * @property integer $subcriterio_fk
 * @property integer $processo_fk
 * @property integer $numero_nota
 * @property string $data_log
 * @property string $id_usuario
 *
 * @property mixed $processoFk
 * @property mixed $subcriterioFk
 */
abstract class BaseSubrisco extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{subrisco}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Sub-risco|Sub-riscos', $n);
	}

	public static function representingColumn() {
		return 'data_log';
	}

	public function rules() {
		return array(
			array('subcriterio_fk, processo_fk, numero_nota, data_log, id_usuario, valor_exercicio', 'required'),
			array('subcriterio_fk, processo_fk, numero_nota', 'numerical', 'integerOnly'=>true),
			array('numero_nota, id_usuario', 'numerical', 'integerOnly'=>true),
			array('id, subcriterio_fk, processo_fk, numero_nota, data_log, id_usuario', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'processoFk' => array(self::BELONGS_TO, 'processo', 'processo_fk'),
			'subcriterioFk' => array(self::BELONGS_TO, 'subcriterio', 'subcriterio_fk'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'subcriterio_fk' => null,
			'processo_fk' => null,
			'numero_nota' => Yii::t('app', 'Numero Nota'),
			'data_log' => Yii::t('app', 'Data Log'),
			'id_usuario' => Yii::t('app', 'Id Usuario'),
			'processoFk' => null,
			'subcriterioFk' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('subcriterio_fk', $this->subcriterio_fk);
		$criteria->compare('processo_fk', $this->processo_fk);
		$criteria->compare('numero_nota', $this->numero_nota);
		$criteria->compare('data_log', $this->data_log, true);
		$criteria->compare('id_usuario', $this->id_usuario, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}