<?php
/********************************************************************************
*  Copyright 2015 Conab - Companhia Nacional de Abastecimento                   *
*                                                                               *
*  Este arquivo é parte do Sistema SIAUDI.                                      *
*                                                                               *
*  SIAUDI  é um software livre; você pode redistribui-lo e/ou                   *
*  modificá-lo sob os termos da Licença Pública Geral GNU conforme              *
*  publicada pela Free Software Foundation; tanto a versão 2 da                 *
*  Licença, como (a seu critério) qualquer versão posterior.                    *
*                                                                               *
*  SIAUDI é distribuído na expectativa de que seja útil,                        *
*  porém, SEM NENHUMA GARANTIA; nem mesmo a garantia implícita                  *
*  de COMERCIABILIDADE OU ADEQUAÇÃO A UMA FINALIDADE ESPECÍFICA.                *
*  Consulte a Licença Pública Geral do GNU para mais detalhes em português:     *
*  http://creativecommons.org/licenses/GPL/2.0/legalcode.pt                     *
*                                                                               *
*  Você deve ter recebido uma cópia da Licença Pública Geral do GNU             *
*  junto com este programa; se não, escreva para a Free Software                *
*  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA    *
*                                                                               *
*  Sistema   : SIAUDI - Sistema de Auditoria Interna                            *
*  Data      : 05/2015                                                          *
*                                                                               *
********************************************************************************/
?>
<?php

/**
 * This is the model base class for the table "{{avaliacao}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Avaliacao".
 *
 * Columns in table "{{avaliacao}}" available as properties of the model,
 * followed by relations of table "{{avaliacao}}" available as properties of the model.
 *
 * @property string $id
 * @property string $relatorio_fk
 * @property string $unidade_administrativa_fk
 * @property string $auditor_fk
 *
 * @property mixed $relatorioFk
 * @property mixed $auditorFk
 */
abstract class BaseAvaliacao extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{avaliacao}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Avaliação|Avaliações', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('id, relatorio_fk, unidade_administrativa_fk, usuario_fk, date, nome_login', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'relatorioFk' => array(self::BELONGS_TO, 'Relatorio', 'relatorio_fk'),
			'usuarioFk' => array(self::BELONGS_TO, 'Usuario', 'usuario_fk'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'relatorio_fk' => null,
			'unidade_administrativa_fk' => Yii::t('app', 'Unidade Administrativa Fk'),
			'usuario_fk' => null,
			'relatorioFk' => null,
			'usuarioFk' => null,
                        'observacao' => Yii::t('app', 'Observação'),
                        'data' => null,
                        'nome_login' => null,
                        'valor_exercicio' => Yii::t('app', 'Exercício'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;
		$criteria->compare('id', $this->id, true);
		$criteria->compare('relatorio_fk', $this->relatorio_fk);
		$criteria->compare('unidade_administrativa_fk', $this->unidade_administrativa_fk, true);
		$criteria->compare('usuario_fk', $this->usuario_fk);
                $criteria->compare('data', $this->data);
                $criteria->compare('nome_login', $this->nome_login);
		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}