<?php
/********************************************************************************
*  Copyright 2015 Conab - Companhia Nacional de Abastecimento                   *
*                                                                               *
*  Este arquivo é parte do Sistema SIAUDI.                                      *
*                                                                               *
*  SIAUDI  é um software livre; você pode redistribui-lo e/ou                   *
*  modificá-lo sob os termos da Licença Pública Geral GNU conforme              *
*  publicada pela Free Software Foundation; tanto a versão 2 da                 *
*  Licença, como (a seu critério) qualquer versão posterior.                    *
*                                                                               *
*  SIAUDI é distribuído na expectativa de que seja útil,                        *
*  porém, SEM NENHUMA GARANTIA; nem mesmo a garantia implícita                  *
*  de COMERCIABILIDADE OU ADEQUAÇÃO A UMA FINALIDADE ESPECÍFICA.                *
*  Consulte a Licença Pública Geral do GNU para mais detalhes em português:     *
*  http://creativecommons.org/licenses/GPL/2.0/legalcode.pt                     *
*                                                                               *
*  Você deve ter recebido uma cópia da Licença Pública Geral do GNU             *
*  junto com este programa; se não, escreva para a Free Software                *
*  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA    *
*                                                                               *
*  Sistema   : SIAUDI - Sistema de Auditoria Interna                            *
*  Data      : 05/2015                                                          *
*                                                                               *
********************************************************************************/
?>
<?php

/**
 * This is the model base class for the table "{{risco}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Risco".
 *
 * Columns in table "{{risco}}" available as properties of the model,
 * followed by relations of table "{{risco}}" available as properties of the model.
 *
 * @property string $id
 * @property string $acao_fk
 * @property string $criterio_fk
 * @property integer $numero_nota
 * @property string $data_log
 * @property string $id_usuario_log
 *
 * @property mixed $acaoFk
 * @property mixed $criterioFk
*/

abstract class BaseRisco extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{subrisco}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Risco|Riscos', $n);
	}

	public static function representingColumn() {
		return 'data_log';
	}

	public function rules() {
		return array(
			array('processo_fk, criterio_fk, numero_nota, data_log, id_usuario_log ', 'required'),
			array('numero_nota', 'numerical', 'integerOnly'=>true),
			array('processo_fk, criterio_fk, numero_nota, id_usuario_log', 'numerical', 'integerOnly'=>true),
			array('id, processo_fk, criterio_fk, numero_nota, data_log, id_usuario_log', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'processoFk' => array(self::BELONGS_TO, 'Processo', 'processo_fk'),
			'criterioFk' => array(self::BELONGS_TO, 'Criterio', 'criterio_fk'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'criterio_fk' => null,
			'numero_nota' => Yii::t('app', 'Numero Nota'),
			'data_log' => Yii::t('app', 'Data Log'),
			'id_usuario_log' => Yii::t('app', 'Id Usuario Log'),
			'acaoFk' => null,
			'criterioFk' => null,
			'processoFk' => null,                    
			'processo_Fk' => null,                    
		);
	}

/*	public function search() {
		$criteria = new CDbCriteria;
		$criteria->compare('id', $this->id, true);
		$criteria->compare('acao_fk', $this->acao_fk);
		$criteria->compare('criterio_fk', $this->criterio_fk);
		$criteria->compare('numero_nota', $this->numero_nota);
		$criteria->compare('data_log', $this->data_log, true);
		$criteria->compare('id_usuario_log', $this->id_usuario_log, true);
		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}*/
}