<?php
/********************************************************************************
*  Copyright 2015 Conab - Companhia Nacional de Abastecimento                   *
*                                                                               *
*  Este arquivo é parte do Sistema SIAUDI.                                      *
*                                                                               *
*  SIAUDI  é um software livre; você pode redistribui-lo e/ou                   *
*  modificá-lo sob os termos da Licença Pública Geral GNU conforme              *
*  publicada pela Free Software Foundation; tanto a versão 2 da                 *
*  Licença, como (a seu critério) qualquer versão posterior.                    *
*                                                                               *
*  SIAUDI é distribuído na expectativa de que seja útil,                        *
*  porém, SEM NENHUMA GARANTIA; nem mesmo a garantia implícita                  *
*  de COMERCIABILIDADE OU ADEQUAÇÃO A UMA FINALIDADE ESPECÍFICA.                *
*  Consulte a Licença Pública Geral do GNU para mais detalhes em português:     *
*  http://creativecommons.org/licenses/GPL/2.0/legalcode.pt                     *
*                                                                               *
*  Você deve ter recebido uma cópia da Licença Pública Geral do GNU             *
*  junto com este programa; se não, escreva para a Free Software                *
*  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA    *
*                                                                               *
*  Sistema   : SIAUDI - Sistema de Auditoria Interna                            *
*  Data      : 05/2015                                                          *
*                                                                               *
********************************************************************************/
?>
<?php

/**
 * This is the model base class for the table "public.vw_usuario_perfil_sistema".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "VwUsuarioPerfilSistema".
 *
 * Columns in table "public.vw_usuario_perfil_sistema" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id_usuario
 * @property string $id_perfil
 * @property string $id_sistema
 *
 */
abstract class BaseVwUsuarioPerfilSistema extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'siaudi.vw_usuario_perfil_sistema';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'VwUsuarioPerfilSistema|VwUsuarioPerfilSistemas', $n);
	}

	public static function representingColumn() {
		return 'id_usuario';
	}

	public function rules() {
		return array(
			array('id_usuario, id_perfil, id_sistema', 'safe'),
			array('id_usuario, id_perfil, id_sistema', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_usuario, id_perfil, id_sistema', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_usuario' => Yii::t('app', 'Id Usuario'),
			'id_perfil' => Yii::t('app', 'Id Perfil'),
			'id_sistema' => Yii::t('app', 'Id Sistema'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_usuario', $this->id_usuario, true);
		$criteria->compare('id_perfil', $this->id_perfil, true);
		$criteria->compare('id_sistema', $this->id_sistema, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}